name: Github Workflow

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          # - 3.8-dev
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Test with Pytest
      run: pytest
